"""add users table

Revision ID: e9af8804b645
Revises: fd9104deafe1
Create Date: 2025-11-07 23:42:16.847648

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e9af8804b645'
down_revision: Union[str, Sequence[str], None] = 'fd9104deafe1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ip_kinds',
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('category', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('term', sa.String(length=128), nullable=True),
    sa.Column('registry', sa.String(length=255), nullable=True),
    sa.Column('notes', sa.String(length=2048), nullable=True),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_table('knowledge_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('title')
    )
    op.create_index(op.f('ix_knowledge_categories_id'), 'knowledge_categories', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('counterparties',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('contact_person', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('address', sa.String(length=512), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_counterparties_id'), 'counterparties', ['id'], unique=False)
    op.create_table('ip_objects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('type', sa.Enum('trademark', 'patent', 'copyright', 'other', name='iptype'), nullable=False),
    sa.Column('status', sa.Enum('draft', 'filed', 'registered', 'expired', name='ipstatus'), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('number', sa.String(length=128), nullable=True),
    sa.Column('registration_date', sa.Date(), nullable=True),
    sa.Column('owner_name', sa.String(length=256), nullable=True),
    sa.Column('estimated_value', sa.Float(), nullable=True),
    sa.Column('report_path', sa.String(length=512), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ip_objects_id'), 'ip_objects', ['id'], unique=False)
    op.create_table('knowledge_articles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['knowledge_categories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_knowledge_articles_category_id'), 'knowledge_articles', ['category_id'], unique=False)
    op.create_index(op.f('ix_knowledge_articles_id'), 'knowledge_articles', ['id'], unique=False)
    op.create_table('tm_applications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('applicant_type', sa.Enum('individual', 'company', name='applicanttype'), nullable=False),
    sa.Column('mark_name', sa.String(), nullable=True),
    sa.Column('mark_image_path', sa.String(), nullable=True),
    sa.Column('mark_description', sa.JSON(), nullable=True),
    sa.Column('nice_classes', sa.JSON(), nullable=True),
    sa.Column('documents', sa.JSON(), nullable=True),
    sa.Column('uniqueness_check', sa.JSON(), nullable=True),
    sa.Column('ai_tips', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('checklist_generated', sa.Boolean(), nullable=True),
    sa.Column('documents_generated', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('deadlines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ip_id', sa.Integer(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('kind', sa.String(length=128), nullable=False),
    sa.Column('note', sa.String(length=512), nullable=True),
    sa.Column('notified', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['ip_id'], ['ip_objects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_deadlines_due_date'), 'deadlines', ['due_date'], unique=False)
    op.create_index(op.f('ix_deadlines_id'), 'deadlines', ['id'], unique=False)
    op.create_index(op.f('ix_deadlines_ip_id'), 'deadlines', ['ip_id'], unique=False)
    op.create_index('ix_deadlines_ip_id_due_date', 'deadlines', ['ip_id', 'due_date'], unique=False)
    op.create_table('documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ip_id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('filepath', sa.String(length=512), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('counterparty_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['counterparty_id'], ['counterparties.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['ip_id'], ['ip_objects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_documents_id'), 'documents', ['id'], unique=False)
    op.create_table('monitoring_tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ip_object_id', sa.Integer(), nullable=False),
    sa.Column('query', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'running', 'done', 'failed', name='monitoring_status_enum'), nullable=False),
    sa.Column('result_summary', sa.JSON(), nullable=True),
    sa.Column('last_run_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['ip_object_id'], ['ip_objects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_monitoring_tasks_id'), 'monitoring_tasks', ['id'], unique=False)
    op.create_index(op.f('ix_monitoring_tasks_ip_object_id'), 'monitoring_tasks', ['ip_object_id'], unique=False)
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('ip_id', sa.Integer(), nullable=True),
    sa.Column('text', sa.String(length=512), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['ip_id'], ['ip_objects.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_id'), 'notifications', ['id'], unique=False)
    op.create_index(op.f('ix_notifications_ip_id'), 'notifications', ['ip_id'], unique=False)
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.create_foreign_key(None, 'valuation_reports', 'valuation_requests', ['request_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'valuation_requests', 'users', ['user_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'valuation_requests', type_='foreignkey')
    op.drop_constraint(None, 'valuation_reports', type_='foreignkey')
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_ip_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_id'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_monitoring_tasks_ip_object_id'), table_name='monitoring_tasks')
    op.drop_index(op.f('ix_monitoring_tasks_id'), table_name='monitoring_tasks')
    op.drop_table('monitoring_tasks')
    op.drop_index(op.f('ix_documents_id'), table_name='documents')
    op.drop_table('documents')
    op.drop_index('ix_deadlines_ip_id_due_date', table_name='deadlines')
    op.drop_index(op.f('ix_deadlines_ip_id'), table_name='deadlines')
    op.drop_index(op.f('ix_deadlines_id'), table_name='deadlines')
    op.drop_index(op.f('ix_deadlines_due_date'), table_name='deadlines')
    op.drop_table('deadlines')
    op.drop_table('tm_applications')
    op.drop_index(op.f('ix_knowledge_articles_id'), table_name='knowledge_articles')
    op.drop_index(op.f('ix_knowledge_articles_category_id'), table_name='knowledge_articles')
    op.drop_table('knowledge_articles')
    op.drop_index(op.f('ix_ip_objects_id'), table_name='ip_objects')
    op.drop_table('ip_objects')
    op.drop_index(op.f('ix_counterparties_id'), table_name='counterparties')
    op.drop_table('counterparties')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_knowledge_categories_id'), table_name='knowledge_categories')
    op.drop_table('knowledge_categories')
    op.drop_table('ip_kinds')
    # ### end Alembic commands ###
