"""add valuation_requests table

Revision ID: fd9104deafe1
Revises: 7f566bd91585
Create Date: 2025-11-07 19:01:37.405308

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fd9104deafe1'
down_revision: Union[str, Sequence[str], None] = '7f566bd91585'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('valuation_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('ip_type', sa.String(length=50), nullable=False),
    sa.Column('jurisdictions', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('brand_strength', sa.Integer(), nullable=False),
    sa.Column('annual_revenue', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('royalty_rate', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('remaining_years', sa.Integer(), nullable=False),
    sa.Column('market_reach', sa.String(length=30), nullable=False),
    sa.Column('industry', sa.String(length=80), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('ai_context', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_valuation_requests_user_id'), 'valuation_requests', ['user_id'], unique=False)
    op.create_table('valuation_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('request_id', sa.Integer(), nullable=False),
    sa.Column('baseline_value', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('ai_adjustment', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('final_value', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('multiples_used', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('risk_discount', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('pdf_path', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('valuation_reports')
    op.drop_index(op.f('ix_valuation_requests_user_id'), table_name='valuation_requests')
    op.drop_table('valuation_requests')
    # ### end Alembic commands ###
